insert into alien values (101,'Navin','Java')
insert into alien values (102,'pravin','PHP')
insert into alien values (103,'komal','Java')
insert into alien values (104,'kiran','Android')
insert into alien values (105,'Rafiq','Android')